<?php
if(!empty($_SESSION['ERP_Uprivileges']) && $ERP_Utype!=1){ //print_r($ses_privileges);

$user_privileges=array(
'states'=>'CMS_STS',
'states_add'=>'CMS_STS_ADD',
'districts'=>'CMS_DTS',
'districts_add'=>'CMS_DTS_ADD',
'mandals'=>'CMS_MDS',
'mandals_add'=>'CMS_MDS_ADD',
'locations'=>'CMS_LOC',
'locations_add'=>'CMS_LOC_ADD',
'gallery_categories'=>'CMS_GALL',
'gallery_add'=>'CMS_GALL',
'news_events'=>'CMS_GALL',
'news_events_add'=>'CMS_GALL',
'payment_categories'=>'CMS_PAYM',
'payment_categories_add'=>'CMS_PAYM_ADD',
'categories'=>'SH_CAT',
'categories_add'=>'SH_CAT_ADD',
'sub_categories'=>'SH_SCAT',
'sub_categories_add'=>'SH_SCAT_ADD',
'items'=>'SH_ITM',
'items_add'=>'SH_ITM_ADD',
'sub_items'=>'SH_SUB_ITM',
'sub_items_add'=>'SH_SUB_ITM_ADD',
'bshgs_registration'=>'BSHGS_REG_MNG',
'bshgs_payment_add'=>'BSHGS_PAY_ADD',
'bshgs_payments'=>'BSHGS_PAY_MNG',
'bsm_registration'=>'BSM_REG_MNG',
'bsm_payment_add'=>'BSM_PAY_ADD',
'bsm_payments'=>'BSM_PAY_MNG',
'biba_registration'=>'BIBA_REG_MNG',
'biba_payment_add'=>'BIBA_PAY_ADD',
'biba_payments'=>'BIBA_PAY_MNG',
'bps_registration'=>'BPS_REG_MNG',
'bps_payment_add'=>'BPS_PAY_ADD',
'bps_payments'=>'BPS_PAY_MNG',
'bns_registration'=>'BNS_REG_MNG',
'bns_payment_add'=>'BSM_PAY_ADD',
'bns_payments'=>'BNS_PAY_MNG',
'bps_products'=>'BPS_PROD_MNG',
'bshgs_products'=>'BSHGS_PROD_MNG',
'bps_products_add'=>'BPS_PROD_ADD',
'bns_products'=>'BNS_PROD_MNG',
'bns_products_add'=>'BNS_PROD_ADD',
'shgm_registration'=>'SHGM_REG_MNG',
'bsm_products'=>'BSM_PROD_MNG',
'regcategories'=>'MNG_REGCAT',
'regsub_categories'=>'MNG_REGSUBCAT',
'regfee'=>'MNG_REGFEE',
'regcategories_add'=>'ADD_REGCAT',
'regsub_categories_add'=>'ADD_REGSUBCAT',
'regfee_add'=>'ADD_REGFEE',
'deals_add'=>'ADD_DLOFF',
'deals'=>'MNG_DLOFF',
'biba_deals'=>'BIBA_DEALS_MNG',
'biba_deals_add'=>'BIBA_DEALS_ADD',
'fpo_payments'=>'FPO_PAY_MNG',
'fpo_payments_add'=>'FPO_PAY_ADD',
'fpo_registration'=>'FPO_REG_MNG',
'fpo_registration_add'=>'FPO_REG_ADD',
'employee_reports'=>'EMP_REP_MNG',
'employee_reports_add'=>'EMP_REP_ADD',
'mitra_reports'=>'EMP_REP_MIT_MNG',
'mitra_reports_add'=>'EMP_REP_MIT_ADD',
'bibad_registration'=>'BIBAD_REG_MNG',
'bibad_registration_add'=>'BIBAD_REG_ADD',
'bibad_payments'=>'BIBAD_PAY_MNG',
'bibad_payments_add'=>'BIBAD_PAY_ADD',
'bibad_products'=>'BIBAD_PROD_MNG',
'bibad_products_add'=>'BIBAD_PROD_ADD',
'faq_categories'=>'FAQ_CAT',
'faq_categories_add'=>'FAQ_CAT_ADD',
'faq_sub_categories'=>'FAQ_SCAT',
'faq_sub_categories_add'=>'FAQ_SCAT_ADD',
'faqs'=>'FAQ_MNG',
'faqs_add'=>'FAQ_ADD',
'inventory_items'=>'INV_ITMS',
'inventory_items_add'=>'INV_ITMS_ADD',
'units'=>'SH_UNITS',
'units_add'=>'SH_UNITS_ADD',
'sub_units'=>'SH_SUB_UNITS',
'sub_units_add'=>'SH_SUNITS_ADD',
'contact_us'=>'CMS_CONTACT',
'bps_quotations'=>'BPS_QUOTATIONS',
'bps_quotations_add'=>'BPS_QUOTATIONS_ADD',
'stock_point'=>'STK_REG_MNG',
'stock_point_add'=>'STK_REG_ADD',
'gst'=>'CMS_GST',
'gst_add'=>'CMS_GST_ADD',
'login_chk'=>'DBORD','employee_add'=>'ADM_ADD','employees'=>'ADM_MNG','view'=>'VIEW','change_password'=>'DBORD','profile'=>'DBORD','profile-edit'=>'DBORD','logout_idle'=>'DBORD','admin_add'=>'ADM_A','admins'=>'ADM_M','dashboard'=>'DBORD','ajax'=>'DBORD');
$page_name= RNSFI;
if($pg=='add'){
$page_name=$page_name."_add";
} 
if(preg_match("/_view/", RNSFI)){
$page_name="view";
}
/*if($_SESSION['ERP_Utype']=='4' && !empty($getid) && preg_match("/student_add/", RNSFI) ){
$page_name=$page_name."_edit";
}*/
//echo $page_name;
$page_pri=$user_privileges[$page_name];
//echo $page_pri;
if(!in_array($page_pri, $ses_privileges)){ 
header("Location:".$baseurl."html/dashboard.php?msg=no_access");
}
}
?>